name: Pull Request Validate

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validate:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Dummy Step
        run: |
          echo 'This is a dummy step'
